// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf.proto

package org.dataaccess.protobuf;

public interface OrderItemOrBuilder extends
    // @@protoc_insertion_point(interface_extends:OrderItem)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  int getId();

  /**
   * <code>.Order order = 2;</code>
   * @return Whether the order field is set.
   */
  boolean hasOrder();
  /**
   * <code>.Order order = 2;</code>
   * @return The order.
   */
  org.dataaccess.protobuf.Order getOrder();
  /**
   * <code>.Order order = 2;</code>
   */
  org.dataaccess.protobuf.OrderOrBuilder getOrderOrBuilder();

  /**
   * <code>.Product product = 3;</code>
   * @return Whether the product field is set.
   */
  boolean hasProduct();
  /**
   * <code>.Product product = 3;</code>
   * @return The product.
   */
  org.dataaccess.protobuf.Product getProduct();
  /**
   * <code>.Product product = 3;</code>
   */
  org.dataaccess.protobuf.ProductOrBuilder getProductOrBuilder();
}
