// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf.proto

package org.dataaccess.protobuf;

public interface OrdersOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Orders)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .Order order = 1;</code>
   */
  java.util.List<org.dataaccess.protobuf.Order> 
      getOrderList();
  /**
   * <code>repeated .Order order = 1;</code>
   */
  org.dataaccess.protobuf.Order getOrder(int index);
  /**
   * <code>repeated .Order order = 1;</code>
   */
  int getOrderCount();
  /**
   * <code>repeated .Order order = 1;</code>
   */
  java.util.List<? extends org.dataaccess.protobuf.OrderOrBuilder> 
      getOrderOrBuilderList();
  /**
   * <code>repeated .Order order = 1;</code>
   */
  org.dataaccess.protobuf.OrderOrBuilder getOrderOrBuilder(
      int index);
}
