// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf.proto

package org.dataaccess.protobuf;

public interface OrderItemsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:OrderItems)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .OrderItem orderItems = 1;</code>
   */
  java.util.List<org.dataaccess.protobuf.OrderItem> 
      getOrderItemsList();
  /**
   * <code>repeated .OrderItem orderItems = 1;</code>
   */
  org.dataaccess.protobuf.OrderItem getOrderItems(int index);
  /**
   * <code>repeated .OrderItem orderItems = 1;</code>
   */
  int getOrderItemsCount();
  /**
   * <code>repeated .OrderItem orderItems = 1;</code>
   */
  java.util.List<? extends org.dataaccess.protobuf.OrderItemOrBuilder> 
      getOrderItemsOrBuilderList();
  /**
   * <code>repeated .OrderItem orderItems = 1;</code>
   */
  org.dataaccess.protobuf.OrderItemOrBuilder getOrderItemsOrBuilder(
      int index);
}
