// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf.proto

package org.dataaccess.protobuf;

public interface UserAddressOrBuilder extends
    // @@protoc_insertion_point(interface_extends:UserAddress)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.Address address = 1;</code>
   * @return Whether the address field is set.
   */
  boolean hasAddress();
  /**
   * <code>.Address address = 1;</code>
   * @return The address.
   */
  org.dataaccess.protobuf.Address getAddress();
  /**
   * <code>.Address address = 1;</code>
   */
  org.dataaccess.protobuf.AddressOrBuilder getAddressOrBuilder();

  /**
   * <code>string username = 2;</code>
   * @return The username.
   */
  java.lang.String getUsername();
  /**
   * <code>string username = 2;</code>
   * @return The bytes for username.
   */
  com.google.protobuf.ByteString
      getUsernameBytes();
}
